# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba53de3b5b9f534b1063af46c8e4705dbcfa8df5979db2a8fb57fd974aea58a90ca14b13deeab78be742a00879f2f8e88fa4e69be122d4b219454acd815bbc1e

test:
  secret_key_base: 1de392b320c7b41f207f02043c0163c389203c0937ef5a0a52fed5828b60b405d19705f3f0692139d25a5475dd4b3554835edc8cc8f13cb3f963c84256feb22c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
